---
title: "HW 4: Clustering and Regression"
author: "Kaori Hirano"
date: "07/11/2023"
format: pdf
---

# Packages

```{r load-packages}
suppressPackageStartupMessages(library(tidyverse))
library(ISLR2)
library(broom) # for tidy function
library(patchwork) # for plot placement
library(ggdendro) # for dendrograms
library(mdsr) # for later examples
library(ggplot2)
suppressPackageStartupMessages(library(openintro))
```

# Data

```{r import-data}
data('evals')
```

# Exercises

## Data Prep

### Q1

```{r q1}
# assigns num times a prof teaches a class to total courses a prof teaches into new dataframe
d <- evals %>% group_by(prof_id) %>% mutate(count = n())

d$prof_num_cls <- d$count

```
### Q2
```{r q2}
# removes course id, prof id, and cls did eval
d <- d %>% select(-one_of('course_id', 'prof_id', 'cls_did_eval'))

# removes bty flower through btymupper
d <- d %>% select(-(bty_f1lower:bty_m2upper))
# names(d)

# splits data in training and test set by 70/30
set.seed(280)
train <- sample(c(TRUE, FALSE), nrow(d),
     replace = TRUE, prob=c(.7,.3))
test <- (!train)
```

## Clustering and Modeling

```{r add-cluster}
add_cluster <- function(col_name, data, cluster_num) {
evals_kmeans <- kmeans(data %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = cluster_num, nstart = 50)
# cluster assignment
data['col_name'] <- evals_kmeans$cluster
}

```

```{r manually-adding-clusters}
# adding clusters to dataset
# because my function didn't work :(

# adds 2
evals_kmeans <- kmeans(d[train,] %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 2, nstart = 50)
# cluster assignment

# this was working JUST FINE yesterday now I have no idea what's wrong
d <- d %>%
mutate(c2 = evals_kmeans$cluster)

# adds 3
evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 3, nstart = 50)
# cluster assignment
d <- d %>%
mutate(c3 = evals_kmeans$cluster)

# adds 4
evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 4, nstart = 50)
# cluster assignment
d <- d %>%
mutate(c4 = evals_kmeans$cluster)

# adds 5
evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 5, nstart = 50)
# cluster assignment
d <- d %>%
mutate(c5 = evals_kmeans$cluster)

# adds 6
evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 6, nstart = 50)
# cluster assignment
d <- d %>%
mutate(c6 = evals_kmeans$cluster)

# adds 7
evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 7, nstart = 50)
# cluster assignment
d <- d %>%
mutate(c7 = evals_kmeans$cluster)

# adds 8
evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 8, nstart = 50)
# cluster assignment
d <- d %>%
mutate(c8 = evals_kmeans$cluster)

# adds 9
evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 9, nstart = 50)
# cluster assignment
d <- d %>%
mutate(c9 = evals_kmeans$cluster)

# adds 10
evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = 10, nstart = 50)
# cluster assignment
d <- d %>%
mutate(c10 = evals_kmeans$cluster)
```

```{r cv-q3}
set.seed(281)
# code here
cv_error_10 <- rep(2, 10)

for(i in seq_along(cv_error_10)){
  evals_kmeans <- kmeans(d %>% select(-one_of('rank', 'ethnicity', 'gender','language', 'cls_level', 'cls_profs', 'cls_credits', 'pic_outfit', 'pic_color')), centers = i, nstart = 50)
  
  
  cv_error_10[i] <- cv.glm(Auto, glmfit = glm_fit, K = 10)$delta[1]
}
cv_error_10


library(fpc)
asw <- numeric(10)
for (k in 2:10) {
  asw[[k]] <- pam(d, k) $ silinfo $ avg.width
  }
k.best <- which.max(asw)
cat("silhouette-optimal number of clusters:", k.best, "\n")
??pam

# so i have to learn how to get a silhouette coefficient? idk what that is... and look for the max there
# or be able to plot the elbow plot
```
```{r out-of-sample-error}
# code here
```

## Lasso
```{r q5}
# code here
```
```{r q1}
# code here
```
```{r q1}
# code here
```

## Comparing Approaches